### ISSUE TITLE
Missing hibp-api-key

### ISSUE THREAD

**Issue by con2net** [icawebdesign/hibp-php#12]
Hi Ian, 

just tried to update my extension with your version 5.2 but I get an error while exploring breached sites by email-address.

With `$breach = new Breach(new HibpHttp($this->APIKey))` I get:

`[2023-04-11 14:08:06] request.CRITICAL: Uncaught PHP Exception GuzzleHttp\Exception\ClientException: "Client error: `GET https://haveibeenpwned.com/api/v3/breachedaccount/paul.paulsen%40gmx.net?truncateResponse=false&includeUnverified=false` resulted in a `401 Unauthorized` response: { "statusCode": 401, "message": "Access denied due to missing hibp-api-key." } " at /var/www/clients/client1/web31/web/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php line 113 {"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 401): Client error: `GET https://haveibeenpwned.com/api/v3/breachedaccount/paul.paulsen%40gmx.net?truncateResponse=false&includeUnverified=false` resulted in a `401 Unauthorized` response:\n{ \"statusCode\": 401, \"message\": \"Access denied due to missing hibp-api-key.\" }\n at /var/www/clients/client1/web31/web/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)"} []`

I have a valid apikey from hibp, but for some reasons, the new version didn´t recognize it?

Any idea what I might have missed?

**Comment by icawebdesign** [comment]
Hi Stefan..

Thanks for reporting this (and the followup email with more detail). Let me look into this and see why it's failing.

**Comment by icawebdesign** [comment]
Thanks agian for reporting this Stefan. You should find this fixed now in both the `5.3` release and `6.1` release.
