### ISSUE TITLE
List on haveibeenpwned.com API consumers list

### ISSUE THREAD

**Issue by Schparky** [icawebdesign/hibp-php#2]
Having looked through several PHP client libraries for HIBP, I found this to be the best. Would be helpful for others to find it at https://haveibeenpwned.com/API/Consumers. Just need to contact [Troy Hunt](https://www.troyhunt.com/contact/).

**Comment by icawebdesign** [comment]
Thanks for the suggestion @Schparky. I've submitted a request to Troy to see if I can get it added :)

**Comment by icawebdesign** [comment]
This has been added by Troy now 👍
