### ISSUE TITLE
timeout?

### ISSUE THREAD

**Issue by brianbrownton** [icawebdesign/hibp-php#6]
if i want to use this library to check partial password hashes, is there an ability to set a timeout so that i can plan for the possibility of this 3rd party api being down?

**Comment by brianbrownton** [comment]
@icawebdesign

**Comment by icawebdesign** [comment]
The `PwnedPasswd` methods have now been covered by this. I'll expand this to cover all methods before marking this as done.

**Comment by icawebdesign** [comment]
These have been implemented into the latest (5.0.0) release. However, 5.0.0 drops support for PHP <7.4 so will back port these changes to the 4.x branch, which will likely be the last (less any security concerns) release under the 4.x version.

**Comment by icawebdesign** [comment]
Completed. All API consumption methods now have an `options` array param available for the `hibp-php4` branch. I'll close this issue now.

Thanks @brianbrownton for the suggestion for this feature 👍🏻
